# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APP_NAME}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ${APP_NAME}
  template:
    metadata:
      labels:
        app: ${APP_NAME}
    strategy:
      type: RollingUpdate
      rollingUpdate:
        # 在更新期间，最多可以比期望的副本数多出多少个 Pod。可以为数字或百分比。
        # (5 个副本 + 25% surge = 最多 6 个 Pod 处于运行状态)
        maxSurge: 25%
        # 在更新期间，最多可以有多少个 Pod 处于不可用状态。可以为数字或百分比。
        # (5 个副本 - 25% unavailable = 至少 4 个 Pod 必须保持可用)
        maxUnavailable: 25%
    spec:
      volumes:
        - name: ${APP_NAME}-config
          configMap:
            name: ${APP_NAME}-config
      containers:
        - name: ${APP_NAME}
          image: ${REGISTRY}/${APP_NAME}-${ENV}:${IMAGE_TAG}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: ${PORT}
          volumeMounts:
            - name: ${APP_NAME}-config
              mountPath: /app/${APP_NAME}.yaml
              subPath: ${APP_NAME}.yaml
---
# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: ${APP_NAME}-service
spec:
  selector:
    app: ${APP_NAME}
  ports:
    - port: ${PORT}
      targetPort: ${PORT}
  type: ClusterIP  # 集群内访问
