# CLI.
gfcli:
  gen:
    dao:
      - link:            "mysql:root:root@tcp(127.0.0.1:3306)/collection"
        tables:          "ct_steps"
        removePrefix:    "ct_"
        descriptionTag:  true
        noModelComment:  true
        path: "./internal/app/collect"
